# Generated by Django 3.0.5 on 2020-04-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpasswordinfo',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
