# Generated by Django 3.0.5 on 2020-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_loginpasswordinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpasswordinfo',
            name='login',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loginpasswordinfo',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
